# Generated by Django 3.0.5 on 2020-05-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200506_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descricao',
            new_name='description',
        ),
    ]
